2024-01-20 17:34:07,797 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2024-01-20 17:34:07,797 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Users\deepi\AppData\Local\Programs\Python\Python311\Lib\site-packages\instabot\bot\bot.py
2024-01-20 17:34:07,798 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2024-01-20 17:34:08,897 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [200]>
2024-01-20 17:34:09,330 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2024-01-20 17:34:10,000 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2024-01-20 17:34:10,357 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [200]>
2024-01-20 17:34:11,255 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [400]>
2024-01-20 17:34:11,256 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"The username you entered doesn\'t appear to belong to an account. Please check your username and try again.","status":"fail","error_type":"ip_block"}'
2024-01-20 17:34:11,256 - instabot version: 0.117.0 (api) - ERROR - Request returns 400 error!
2024-01-20 17:34:11,256 - instabot version: 0.117.0 (api) - INFO - Instagram's error message: The username you entered doesn't appear to belong to an account. Please check your username and try again.
2024-01-20 17:34:11,257 - instabot version: 0.117.0 (api) - INFO - Error type: ip_block
2024-01-20 17:34:11,257 - instabot version: 0.117.0 (api) - ERROR - Failed to login go to instagram and change your password
2024-01-20 17:34:11,258 - instabot version: 0.117.0 (api) - INFO - Username or password is incorrect.
